# Site settings
title: "Senior Technical Writer Screening Test"
description: "Submitted by Pavani Eli"
author:
  name: Pavani Eli
  email: pavani.eli@email.com

theme: jekyll-theme-minimal

# Optional: Add navigation links
plugins:
  - jekyll-seo-tag

